### ISSUE TITLE
🐛 Process won't stop

### ISSUE THREAD

**Issue by LeoTT** [process-engine/process_engine_runtime#51] opened 2018-09-11 15:17 UTC
#### Describe your issue

Have a diagram with some weird behaviour. 

1. On the first try the process stopped directly without executing the user task(this does not always happen with this diagram, only sometimes).
2. User task seems to be stuck in a loop. According to the diagram the process should stop afterwards.
3. After a while it breaks with the animated loading wheels. I can't navigate out of the waiting dialogue (this looks like a bpmn-studio bug).

![bug](https://user-images.githubusercontent.com/21304781/45369130-7cc19600-b5e5-11e8-82b2-8730f1aa0b46.gif)

#### How can others reproduce the issue?

- Run the diagram in bpmn-studio
- Exit bpmn-studio when userTask shows up
- Restart bpmn-studio
- Try to run the process

<details>
  <summary>buggy diagram</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
    <bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:camunda="http://camunda.org/schema/1.0/bpmn" id="Definition_1" targetNamespace="http://bpmn.io/schema/bpmn" exporter="Camunda Modeler" exporterVersion="1.8.0">
        <bpmn:collaboration id="Collaboration_1cidyxu" name="">
            <bpmn:extensionElements>
                <camunda:formData />
            </bpmn:extensionElements>
            <bpmn:participant id="Participant_0px403d" name="HTTP REST API" processRef="HTTP REST API" />
        </bpmn:collaboration>
        <bpmn:process id="HTTP REST API" name="HTTP REST API" isExecutable="true">
            <bpmn:laneSet>
                <bpmn:lane id="Lane_1xzf0d3" name="Lane">
                    <bpmn:flowNodeRef>
                        StartEvent_1
                    </bpmn:flowNodeRef>
                    <bpmn:flowNodeRef>
                        Task_0mk7l1m
                    </bpmn:flowNodeRef>
                    <bpmn:flowNodeRef>
                        EndEvent_1snx2nr
                    </bpmn:flowNodeRef>
                    <bpmn:flowNodeRef>
                        Task_1msdzuo
                    </bpmn:flowNodeRef>
                </bpmn:lane>
            </bpmn:laneSet>
            <bpmn:startEvent id="StartEvent_1" name="HTTP REST API">
                <bpmn:extensionElements>
                    <camunda:executionListener class="" event="" />
                    <camunda:properties />
                    <camunda:properties />
                </bpmn:extensionElements>
                <bpmn:outgoing>
                    SequenceFlow_1ymq7uy
                </bpmn:outgoing>
            </bpmn:startEvent>
            <bpmn:sequenceFlow id="SequenceFlow_1ymq7uy" sourceRef="StartEvent_1" targetRef="Task_0mk7l1m" />
            <bpmn:serviceTask id="Task_0mk7l1m" name="Fetch Data">
                <bpmn:extensionElements>
                    <camunda:executionListener class="" event="" />
                    <camunda:properties>
                        <camunda:property name="module" value="HttpService" />
                        <camunda:property name="method" value="get" />
                        <camunda:property name="params" value="[&#39;http://free.currencyconverterapi.com/api/v5/convert?q=EUR_USD&#38;compact=y&#39;]" />
                    </camunda:properties>
                </bpmn:extensionElements>
                <bpmn:incoming>
                    SequenceFlow_1ymq7uy
                </bpmn:incoming>
                <bpmn:outgoing>
                    SequenceFlow_043p5kp
                </bpmn:outgoing>
            </bpmn:serviceTask>
            <bpmn:sequenceFlow id="SequenceFlow_043p5kp" name="" sourceRef="Task_0mk7l1m" targetRef="Task_1msdzuo">
                <bpmn:extensionElements>
                    <camunda:formData />
                </bpmn:extensionElements>
            </bpmn:sequenceFlow>
            <bpmn:endEvent id="EndEvent_1snx2nr" name="">
                <bpmn:extensionElements>
                    <camunda:executionListener class="" event="" />
                    <camunda:properties />
                </bpmn:extensionElements>
                <bpmn:incoming>
                    SequenceFlow_15vmfjq
                </bpmn:incoming>
            </bpmn:endEvent>
            <bpmn:sequenceFlow id="SequenceFlow_15vmfjq" sourceRef="Task_1msdzuo" targetRef="EndEvent_1snx2nr" />
            <bpmn:userTask id="Task_1msdzuo" name="Show Data">
                <bpmn:extensionElements>
                    <camunda:executionListener class="" event="" />
                    <camunda:properties>
                        <camunda:property name="preferredControl" value="confirm" />
                    </camunda:properties>
                    <camunda:formData>
                        <camunda:formField id="Form_z7DkErSK" label="${&#39;1 EUR =&#39; + token.current.result.EUR_USD.val + &#39;$&#39;}" type="boolean" defaultValue="" />
                    </camunda:formData>
                </bpmn:extensionElements>
                <bpmn:incoming>
                    SequenceFlow_043p5kp
                </bpmn:incoming>
                <bpmn:outgoing>
                    SequenceFlow_15vmfjq
                </bpmn:outgoing>
            </bpmn:userTask>
        </bpmn:process>
        <bpmndi:BPMNDiagram id="BPMNDiagram_1">
            <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Collaboration_1cidyxu">
                <bpmndi:BPMNShape id="Participant_0px403d_di" bpmnElement="Participant_0px403d">
                    <dc:Bounds x="5" y="4" width="581" height="170" />
                </bpmndi:BPMNShape>
                <bpmndi:BPMNShape id="_BPMNShape_StartEvent_2" bpmnElement="StartEvent_1">
                    <dc:Bounds x="101" y="65" width="36" height="36" />
                    <bpmndi:BPMNLabel>
                        <dc:Bounds x="109" y="101" width="21" height="13" />
                    </bpmndi:BPMNLabel>
                </bpmndi:BPMNShape>
                <bpmndi:BPMNShape id="Lane_1xzf0d3_di" bpmnElement="Lane_1xzf0d3">
                    <dc:Bounds x="35" y="4" width="551" height="170" />
                </bpmndi:BPMNShape>
                <bpmndi:BPMNEdge id="SequenceFlow_1ymq7uy_di" bpmnElement="SequenceFlow_1ymq7uy">
                    <di:waypoint x="137" y="83" />
                    <di:waypoint x="182" y="83" />
                    <bpmndi:BPMNLabel>
                        <dc:Bounds x="159.5" y="61.5" width="0" height="13" />
                    </bpmndi:BPMNLabel>
                </bpmndi:BPMNEdge>
                <bpmndi:BPMNShape id="ServiceTask_0qqfijr_di" bpmnElement="Task_0mk7l1m">
                    <dc:Bounds x="182" y="43" width="100" height="80" />
                </bpmndi:BPMNShape>
                <bpmndi:BPMNEdge id="SequenceFlow_043p5kp_di" bpmnElement="SequenceFlow_043p5kp">
                    <di:waypoint x="282" y="83" />
                    <di:waypoint x="322" y="83" />
                    <bpmndi:BPMNLabel>
                        <dc:Bounds x="302" y="61.5" width="0" height="13" />
                    </bpmndi:BPMNLabel>
                </bpmndi:BPMNEdge>
                <bpmndi:BPMNShape id="UserTask_0arkqb5_di" bpmnElement="Task_1msdzuo">
                    <dc:Bounds x="322" y="43" width="100" height="80" />
                </bpmndi:BPMNShape>
                <bpmndi:BPMNShape id="EndEvent_1snx2nr_di" bpmnElement="EndEvent_1snx2nr">
                    <dc:Bounds x="466" y="65" width="36" height="36" />
                    <bpmndi:BPMNLabel>
                        <dc:Bounds x="484" y="104" width="0" height="13" />
                    </bpmndi:BPMNLabel>
                </bpmndi:BPMNShape>
                <bpmndi:BPMNEdge id="SequenceFlow_15vmfjq_di" bpmnElement="SequenceFlow_15vmfjq">
                    <di:waypoint x="422" y="83" />
                    <di:waypoint x="466" y="83" />
                    <bpmndi:BPMNLabel>
                        <dc:Bounds x="444" y="61" width="0" height="13" />
                    </bpmndi:BPMNLabel>
                </bpmndi:BPMNEdge>
            </bpmndi:BPMNPlane>
        </bpmndi:BPMNDiagram>
    </bpmn:definitions>
```
</details>

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment] 2018-09-11 15:33
I put this process directly through the backend and it worked. I'll keep trying to reproduce it with help of the runtime integrationtests, but right know I do not believe this to be an issue with the backend.

**Comment by LeoTT** [comment] 2018-09-12 06:53
Reset my db today and now the problem with the loop no longer appears.
Forgot to make a backup, because I thought it was unrelated(I have reset the db yesterday multiple times when I encountered this).  Will make sure to freeze everything next time I encounter something unexpected.

At least problem number 1 (Process stopping directly) still persists for me. Happens about 30% of the times I start that diagram.

**Comment by ElRaptorus** [comment] 2018-09-12 14:52
@SteffenKn @LeoTT 
It would be helpful, if you could include some info as to what routes are called on the backend, ideally with parameters, payloads and the response you get.

This is very hard to reproduce in the backend.

**Comment by ElRaptorus** [comment] 2018-09-20 08:51
@LeoTT
After @alexanderkasten encountered this issue again yesterday, we were finally able to nail it down.

In short:
We can't resume processes yet. 

In not so short:
This effect occurs, when you do the following:
- Start a process and wait for the UserTask
- Close and  reopen the BPMN Studio
- Try to finish that UserTask

The user task was never finished before the Studio shut down, so it is still marked as active in the database.
However, the ProcessEngine itself is not executing the process anymore, so you can attempt to finish it as often as you want, it will never actually happen.

This is an issue that will be addressed, when we implement the `Resume Process` functionality. 

/cc @SteffenKn @5ebastianMeier @moellenbeck @cmg-dev

**Comment by ElRaptorus** [comment] 2018-09-20 08:52
See: 
https://github.com/process-engine/process_engine_runtime/issues/65

**Comment by ElRaptorus** [comment] 2018-11-07 13:45
I'll close this, as this is effectively a duplicate of #65 and only clutters things up. 

If we still run into this issue, after Process Resumption is done, we can revisit this.

**Closed by ElRaptorus** 2018-11-07 13:45 UTC
Labels: bug, confirmed, duplicate, wontfix
